# Generated by Django 4.2.7 on 2023-12-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadasterrequest",
            name="cadaster_number",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
