# Generated by Django 4.2.7 on 2023-12-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requests", "0002_alter_cadasterrequest_cadaster_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadasterrequest",
            name="cadaster_number",
            field=models.CharField(max_length=100),
        ),
    ]
